import { cloneDeep } from "lodash";
import { Card } from "./card";
import { Colors } from "./color";
import { Rank } from "./rank";

export const getCardList = () => cloneDeep(CARDS_LIST);
const CARDS_LIST = [
  new Card(Colors.BLUE, Rank.ONE),
  new Card(Colors.BLUE, Rank.TWO),
  new Card(Colors.BLUE, Rank.THREE),
  new Card(Colors.BLUE, Rank.FOUR),
  new Card(Colors.BLUE, Rank.FIVE),
  new Card(Colors.BLUE, Rank.SIX),
  new Card(Colors.BLUE, Rank.SEVEN),
  new Card(Colors.BLUE, Rank.EIGHT),
  new Card(Colors.BLUE, Rank.NINE),
  new Card(Colors.BLUE, Rank.TEN),
  new Card(Colors.BLUE, Rank.JACK),
  new Card(Colors.BLUE, Rank.QUEEN),
  new Card(Colors.BLUE, Rank.KING),
  new Card(Colors.RED, Rank.ONE),
  new Card(Colors.RED, Rank.TWO),
  new Card(Colors.RED, Rank.THREE),
  new Card(Colors.RED, Rank.FOUR),
  new Card(Colors.RED, Rank.FIVE),
  new Card(Colors.RED, Rank.SIX),
  new Card(Colors.RED, Rank.SEVEN),
  new Card(Colors.RED, Rank.EIGHT),
  new Card(Colors.RED, Rank.NINE),
  new Card(Colors.RED, Rank.TEN),
  new Card(Colors.RED, Rank.JACK),
  new Card(Colors.RED, Rank.QUEEN),
  new Card(Colors.RED, Rank.KING),
  new Card(Colors.TEAL, Rank.ONE),
  new Card(Colors.TEAL, Rank.TWO),
  new Card(Colors.TEAL, Rank.THREE),
  new Card(Colors.TEAL, Rank.FOUR),
  new Card(Colors.TEAL, Rank.FIVE),
  new Card(Colors.TEAL, Rank.SIX),
  new Card(Colors.TEAL, Rank.SEVEN),
  new Card(Colors.TEAL, Rank.EIGHT),
  new Card(Colors.TEAL, Rank.NINE),
  new Card(Colors.TEAL, Rank.TEN),
  new Card(Colors.TEAL, Rank.JACK),
  new Card(Colors.TEAL, Rank.QUEEN),
  new Card(Colors.TEAL, Rank.KING),
  new Card(Colors.YELLOW, Rank.ONE),
  new Card(Colors.YELLOW, Rank.TWO),
  new Card(Colors.YELLOW, Rank.THREE),
  new Card(Colors.YELLOW, Rank.FOUR),
  new Card(Colors.YELLOW, Rank.FIVE),
  new Card(Colors.YELLOW, Rank.SIX),
  new Card(Colors.YELLOW, Rank.SEVEN),
  new Card(Colors.YELLOW, Rank.EIGHT),
  new Card(Colors.YELLOW, Rank.NINE),
  new Card(Colors.YELLOW, Rank.TEN),
  new Card(Colors.YELLOW, Rank.JACK),
  new Card(Colors.YELLOW, Rank.QUEEN),
  new Card(Colors.YELLOW, Rank.KING),
];
