import { SuiteCard } from "../types/cards/suite-card";
import { Colors } from "../types/cards/colors";
import { Ranks } from "../types/cards/ranks";
import { SpecialCard } from "../types/cards/special-card";
import { Specials } from "../types/cards/specials";
import { Card } from "../types/cards/card";

export const getCardList = () => CARDS_LIST;
const CARDS_LIST: SuiteCard[] = [
  new SuiteCard(Colors.BLUE, Ranks.ONE),
  new SuiteCard(Colors.BLUE, Ranks.TWO),
  new SuiteCard(Colors.BLUE, Ranks.THREE),
  new SuiteCard(Colors.BLUE, Ranks.FOUR),
  new SuiteCard(Colors.BLUE, Ranks.FIVE),
  new SuiteCard(Colors.BLUE, Ranks.SIX),
  new SuiteCard(Colors.BLUE, Ranks.SEVEN),
  new SuiteCard(Colors.BLUE, Ranks.EIGHT),
  new SuiteCard(Colors.BLUE, Ranks.NINE),
  new SuiteCard(Colors.BLUE, Ranks.TEN),
  new SuiteCard(Colors.BLUE, Ranks.JACK),
  new SuiteCard(Colors.BLUE, Ranks.QUEEN),
  new SuiteCard(Colors.BLUE, Ranks.KING),
  new SuiteCard(Colors.RED, Ranks.ONE),
  new SuiteCard(Colors.RED, Ranks.TWO),
  new SuiteCard(Colors.RED, Ranks.THREE),
  new SuiteCard(Colors.RED, Ranks.FOUR),
  new SuiteCard(Colors.RED, Ranks.FIVE),
  new SuiteCard(Colors.RED, Ranks.SIX),
  new SuiteCard(Colors.RED, Ranks.SEVEN),
  new SuiteCard(Colors.RED, Ranks.EIGHT),
  new SuiteCard(Colors.RED, Ranks.NINE),
  new SuiteCard(Colors.RED, Ranks.TEN),
  new SuiteCard(Colors.RED, Ranks.JACK),
  new SuiteCard(Colors.RED, Ranks.QUEEN),
  new SuiteCard(Colors.RED, Ranks.KING),
  new SuiteCard(Colors.TEAL, Ranks.ONE),
  new SuiteCard(Colors.TEAL, Ranks.TWO),
  new SuiteCard(Colors.TEAL, Ranks.THREE),
  new SuiteCard(Colors.TEAL, Ranks.FOUR),
  new SuiteCard(Colors.TEAL, Ranks.FIVE),
  new SuiteCard(Colors.TEAL, Ranks.SIX),
  new SuiteCard(Colors.TEAL, Ranks.SEVEN),
  new SuiteCard(Colors.TEAL, Ranks.EIGHT),
  new SuiteCard(Colors.TEAL, Ranks.NINE),
  new SuiteCard(Colors.TEAL, Ranks.TEN),
  new SuiteCard(Colors.TEAL, Ranks.JACK),
  new SuiteCard(Colors.TEAL, Ranks.QUEEN),
  new SuiteCard(Colors.TEAL, Ranks.KING),
  new SuiteCard(Colors.YELLOW, Ranks.ONE),
  new SuiteCard(Colors.YELLOW, Ranks.TWO),
  new SuiteCard(Colors.YELLOW, Ranks.THREE),
  new SuiteCard(Colors.YELLOW, Ranks.FOUR),
  new SuiteCard(Colors.YELLOW, Ranks.FIVE),
  new SuiteCard(Colors.YELLOW, Ranks.SIX),
  new SuiteCard(Colors.YELLOW, Ranks.SEVEN),
  new SuiteCard(Colors.YELLOW, Ranks.EIGHT),
  new SuiteCard(Colors.YELLOW, Ranks.NINE),
  new SuiteCard(Colors.YELLOW, Ranks.TEN),
  new SuiteCard(Colors.YELLOW, Ranks.JACK),
  new SuiteCard(Colors.YELLOW, Ranks.QUEEN),
  new SuiteCard(Colors.YELLOW, Ranks.KING),
  new SpecialCard(Colors.BLUE, Ranks.JACK, Specials.SKIP_NEXT_USER),
  new SpecialCard(Colors.BLUE, Ranks.KING, Specials.PLUS_ONE),
  new SpecialCard(Colors.BLUE, Ranks.NONE, Specials.SWAP_HANDS),
  new SpecialCard(Colors.BLUE, Ranks.QUEEN, Specials.CHANGE_DIRECTION),
  new SpecialCard(Colors.RED, Ranks.JACK, Specials.SKIP_NEXT_USER),
  new SpecialCard(Colors.RED, Ranks.KING, Specials.PLUS_ONE),
  new SpecialCard(Colors.RED, Ranks.NONE, Specials.SWAP_HANDS),
  new SpecialCard(Colors.RED, Ranks.QUEEN, Specials.CHANGE_DIRECTION),
  new SpecialCard(Colors.TEAL, Ranks.JACK, Specials.SKIP_NEXT_USER),
  new SpecialCard(Colors.TEAL, Ranks.KING, Specials.PLUS_ONE),
  new SpecialCard(Colors.TEAL, Ranks.NONE, Specials.SWAP_HANDS),
  new SpecialCard(Colors.TEAL, Ranks.QUEEN, Specials.CHANGE_DIRECTION),
  new SpecialCard(Colors.YELLOW, Ranks.JACK, Specials.SKIP_NEXT_USER),
  new SpecialCard(Colors.YELLOW, Ranks.KING, Specials.PLUS_ONE),
  new SpecialCard(Colors.YELLOW, Ranks.NONE, Specials.SWAP_HANDS),
  new SpecialCard(Colors.YELLOW, Ranks.QUEEN, Specials.CHANGE_DIRECTION),
  new SpecialCard(Colors.ALL, Ranks.NONE, Specials.WILD_CARD),
  new SpecialCard(Colors.ALL, Ranks.NONE, Specials.WILD_CARD),
  new SpecialCard(Colors.ALL, Ranks.NONE, Specials.WILD_CARD),
  new SpecialCard(Colors.ALL, Ranks.NONE, Specials.WILD_CARD),
];
